language: objective-c
osx_image: xcode8.2

script:
  - set -o pipefail && xcodebuild -project ReactiveKit.xcodeproj -scheme ReactiveKit-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.0' test | xcpretty
  - set -o pipefail && swift build
  - set -o pipefail && swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)
